# Generated by Django 3.2 on 2023-01-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DenormalizedAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.UUIDField(editable=False)),
                ('group', models.UUIDField(editable=False)),
                ('campaign', models.UUIDField(editable=False)),
                ('site', models.UUIDField(editable=False)),
                ('slot', models.UUIDField(editable=False)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'denormalized_advertisement',
                'managed': False,
            },
        ),migrations.RunSQL(
            '''
            CREATE OR REPLACE VIEW denormalized_advertisement
            AS
            SELECT targeting_rule_slot.id,
                advertisements.guid as advertisement,
                advertisementgroup.guid as group,
                campaign.guid as campaign,
                site.guid as site,
                slot.guid as slot,
                targeting_rule.tags as tags,
                advertisements.data as data,
                targeting_rule.created AS created,
                targeting_rule.updated as updated
            FROM advertisements_advertisement advertisements 
                INNER JOIN advertisements_advertisementgroup advertisementgroup ON advertisements.advertisement_group_id = advertisementgroup.id
                INNER JOIN advertisements_campaign campaign on campaign.id = advertisementgroup.campaign_id
                INNER JOIN advertisements_advertisementgrouptargetingrule targeting_rule ON advertisements.advertisement_group_id = targeting_rule.advertisement_group_id
                INNER JOIN advertisements_advertisementgrouptargetingrule_slot targeting_rule_slot ON targeting_rule.id = targeting_rule_slot.advertisementgrouptargetingrule_id
                INNER JOIN publishers_slot slot on slot.id = targeting_rule_slot.slot_id
                INNER JOIN publishers_site site on site.id = slot.site_id
                ORDER BY created DESC;
            '''
        )
    ]
