# Generated by Django 3.2 on 2023-01-21 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_views', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denormalizedadvertisement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 21, 6, 26, 55, 811252, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denormalizedadvertisement',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
